create table if not exists public.produits (
  id bigint primary key,
  nom text not null,
  actif boolean not null default true
);

create table if not exists public.mouvements (
  id bigint generated by default as identity primary key,
  date_mouvement timestamptz not null default now(),
  type text not null check (type in ('ENTREE', 'SORTIE')),
  produit_id bigint not null references public.produits(id),
  quantite integer not null check (quantite > 0),
  nom_secouriste text,
  lot_vpsp text,
  numero_lot text,
  date_peremption date
);

create index if not exists mouvements_produit_idx on public.mouvements(produit_id);
create index if not exists mouvements_date_idx on public.mouvements(date_mouvement desc);

alter table public.produits enable row level security;
alter table public.mouvements enable row level security;

drop policy if exists "lecture produits" on public.produits;
create policy "lecture produits" on public.produits for select using (true);

drop policy if exists "lecture mouvements" on public.mouvements;
create policy "lecture mouvements" on public.mouvements for select using (true);

drop policy if exists "ajout mouvements" on public.mouvements;
create policy "ajout mouvements" on public.mouvements for insert with check (true);
